spring:
  datasource:
    initialization-mode: always

  profiles:
    active: dev

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: admin

